### PR TITLE
Use ctypes.util module to locate dynamic libraries

### PR DESCRIPTION
**Pull request by millerabel**
Updated to use types.util.find_library to locate the cairo, freetype, and fontconfig shared libraries. This function searches all platform-specific usual places, consults environment variables as required, and adds platform-specific prefix, suffix, and is insensitive to version naming. It returns the fully qualified pathname of the location of the dynamic library (so, DLL, or Dylib, etc, ...) that can be passed to ctypes.cdll.LoadLibrary(...) to load the library. This replaces the platform dictionary with hard-coded names.

Also renamed README to README.md so that it will render in CommonMark on GitHub.

### CODE REVIEW

**Comment by ldo** [comment]
There is a reason why the object versions are hard-coded: because a change in those represents potentially incompatible ABI changes.

**Comment by millerabel** [comment]
Hmmm… Best practice is to load dynamic libraries (DLLs, SOs, and Dylibs, all platforms) using the un-decorated name that was used to link the library and allow the end user to manage the current versions (including the filename suffix) they have installed and path they want to search using environment variables. Hard coding prevents this. That’s what find_library() in ctypes.util does.

Here are the best practices for macOS, Windows, and open source Linux projects:

macOS:
https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html <https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html>

Windows:
https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order <https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order>

Linux:
https://opensource.com/article/20/6/linux-libraries <https://opensource.com/article/20/6/linux-libraries> (see the section on Dynamic Loading)
https://www.man7.org/linux/man-pages/man3/dlopen.3.html <https://www.man7.org/linux/man-pages/man3/dlopen.3.html>

I’d encourage you to adopt the change, or to recode that section to accommodate specific concerns you have about ABI compatibility that you think this change will not accommodate. And using the recommended practices for platforms that exhibit ABI compatibility problems. Hardcoding the file names of dynamically loaded libraries renders the module not useable without manual edits to the source code.

— Miller

Miller Abel
***@***.***



On May 20, 2021, at 2:46 PM, ldo ***@***.***> wrote:


There is a reason why the object versions are hard-coded: because a change in those represents potentially incompatible ABI changes.

**Comment by ldo** [comment]
https://akkadia.org/drepper/dsohowto.pdf section 3.3.

**Comment by millerabel** [comment]
While sensitivity to ABI is important, it’s really a packaging and installation concern, not a runtime one. PyPA has moved away from distutils and setuptools and has embraced a new form of packaging called wheels. Wheels are faster to install and more reliable packaging for end users, especially when binary extensions are included. A PiPI distribution now should include at least one wheel as well as the sdist…

https://packaging.python.org/guides/distributing-packages-using-setuptools/ <https://packaging.python.org/guides/distributing-packages-using-setuptools/>

Wheels <https://packaging.python.org/guides/distributing-packages-using-setuptools/#id71>
You should also create a wheel for your project. A wheel is a built package <https://packaging.python.org/glossary/#term-Built-Distribution> that can be installed without needing to go through the “build” process. Installing wheels is substantially faster for the end user than installing from a source distribution.

If your project is pure Python then you’ll be creating a “Pure Python Wheel” (see section below) <https://packaging.python.org/guides/distributing-packages-using-setuptools/#pure-python-wheels>.

If your project contains compiled extensions, then you’ll be creating what’s called a *Platform Wheel* (see section below) <https://packaging.python.org/guides/distributing-packages-using-setuptools/#platform-wheels>.

 <https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels>
Here is a recent article that describes what wheels are, how to build them, why they are a superior complement to source distributions, and how they solve the ABI problem for compiled artifacts. It’s a long but well-written article that works through the full process:

https://realpython.com/python-wheels/ <https://realpython.com/python-wheels/>

What Is a Python Wheel?
A Python .whl file is essentially a ZIP (.zip) archive with a specially crafted filename that tells installers what Python versions and platforms the wheel will support.

A wheel is a type of built distribution <https://packaging.python.org/glossary/#term-built-distribution>. In this case, built means that the wheel comes in a ready-to-install format and allows you to skip the build stage required with source distributions.

A wheel filename is broken down into parts separated by hyphens:

{dist}-{version}(-{build})?-{python}-{abi}-{platform}.whl
Each section in {brackets} is a tag, or a component of the wheel name that carries some meaning about what the wheel contains and where the wheel will or will not work.

Here’s an illustrative example using a cryptography <https://github.com/pyca/cryptography> wheel:

cryptography-2.9.2-cp35-abi3-macosx_10_9_x86_64.whl

 <https://realpython.com/python-wheels/#advantages-of-python-wheels>
Here’s a testament to wheels from the Python Packaging Authority <https://www.pypa.io/en/latest/> (PyPA):

Not all developers have the right tools or experiences to build these components written in these compiled languages, so Python created the wheel, a package format designed to ship libraries with compiled artifacts. In fact, Python’s package installer, pip, always prefers wheels because installation is always faster, so even pure-Python packages work better with wheels.


Repackaging Qahirah as a wheel, and including compatible cairo, freetype, and fontconfig dynamic libraries in each built distribution wheel will eliminate the ABI compatibility problem. There is a special form of Linux wheel platform target called “manyLinux” that can make a pan-Linux target without having to replicate distributions for all of the redundant Linux platforms. 

Building wheels is straight-forward. The manyLinux target is built using a Docker container imaged on CentOS and with the GNU tools. This eliminates build environment discrepancies. It can be built on any build system, Linux (any), macOS, or Windows, and will produce a binary built distribution that can run on any linux system. All external library dependencies are resolved from within the packaged distribution and so don’t rely on the execution environment.

The macOS and Windows wheels may need to be built from the source distribution on those platforms if binary dependencies are being rebuilt, owing to platform-specific build tools (LLVM/Xcode for macOS, e.g.). But it’s possible to bundle already built binary dynamic libraries without rebuilding them using audit-wheel and delocate-wheel (see: https://realpython.com/python-wheels/#bundling-shared-libraries <https://realpython.com/python-wheels/#bundling-shared-libraries>)

"If you’re distributing a package that has external dependencies like this, then you can do your users a favor by using auditwheel or delocate to save them the extra step of installing the dependencies themselves."


Using wheels, it’s now possible to publish distributions for the popular platforms, including all binary dependencies, and also include a source distribution (as you currently do). Users just “pip install qahirah” and PIP 19+ will find the correct platform-specific wheel, download it, and install it. The binary dependencies will not disrupt other versions of those dynamic libraries that are already installed on a user’s system (cairo or freetype, e.g.)

— Miller

Miller Abel
***@***.***



On May 22, 2021, at 5:44 PM, ldo ***@***.***> wrote:


https://akkadia.org/drepper/dsohowto.pdf <https://akkadia.org/drepper/dsohowto.pdf> section 3.3.

**Pull request closed without merging**
